/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import com.sun.jdi.OpaqueFrameException;
import controlador.Manipula;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.*;
import controlador.*;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author otjos
 */
public class VentanaCrearHos extends javax.swing.JDialog
{

    /**
     * Creates new form CrearVentanaDep
     */
    private VentanaPrincipal principal;
    private String rutaActual;

    public VentanaCrearHos(java.awt.Frame parent, boolean modal, VentanaPrincipal principal, String rutaActual)
    {
        super(parent, modal);
        this.principal = principal;
        this.rutaActual = rutaActual;
        initComponents();

        String claveTemporal = String.format("H.%03d", Datos.getContadorGeneral() + 1);
        txtClave.setText(claveTemporal);

        llenarComboDependencias(JCDependencia, Var.getM().getR());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bg = new javax.swing.JPanel();
        bgArb = new javax.swing.JPanel();
        iconPropiedas = new javax.swing.JLabel();
        txtNombreClase = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        Clave1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bgAbj = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();
        JCDependencia = new javax.swing.JComboBox<>();
        Clave2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Clave3 = new javax.swing.JLabel();
        JCNivel1 = new javax.swing.JComboBox<>();
        Clave4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 250));
        setResizable(false);

        bg.setBackground(java.awt.Color.white);
        bg.setMaximumSize(new java.awt.Dimension(300, 250));
        bg.setMinimumSize(new java.awt.Dimension(300, 250));
        bg.setPreferredSize(new java.awt.Dimension(300, 250));

        bgArb.setBackground(new java.awt.Color(102, 153, 255));

        iconPropiedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/hospital.png"))); // NOI18N

        txtNombreClase.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtNombreClase.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreClase.setText("HOSPITAL");

        javax.swing.GroupLayout bgArbLayout = new javax.swing.GroupLayout(bgArb);
        bgArb.setLayout(bgArbLayout);
        bgArbLayout.setHorizontalGroup(
            bgArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgArbLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iconPropiedas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        bgArbLayout.setVerticalGroup(
            bgArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconPropiedas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgArbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Clave.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave.setForeground(new java.awt.Color(51, 51, 51));
        Clave.setText("CLAVE");
        Clave.setToolTipText("");

        Clave1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave1.setForeground(new java.awt.Color(51, 51, 51));
        Clave1.setText("NOMBRE");
        Clave1.setToolTipText("");

        txtClave.setEditable(false);
        txtClave.setBackground(java.awt.Color.white);
        txtClave.setColumns(7);
        txtClave.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        txtClave.setBorder(null);
        txtClave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtClaveActionPerformed(evt);
            }
        });

        txtDireccion.setBackground(java.awt.Color.white);
        txtDireccion.setColumns(45);
        txtDireccion.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.setText("Ingrese la direccion");
        txtDireccion.setBorder(null);
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                txtDireccionMousePressed(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtDireccionActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        bgAbj.setBackground(new java.awt.Color(102, 153, 255));

        btnGuardar.setBackground(new java.awt.Color(102, 153, 255));
        btnGuardar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgAbjLayout = new javax.swing.GroupLayout(bgAbj);
        bgAbj.setLayout(bgAbjLayout);
        bgAbjLayout.setHorizontalGroup(
            bgAbjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgAbjLayout.setVerticalGroup(
            bgAbjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        JCDependencia.setBackground(new java.awt.Color(204, 204, 204));
        JCDependencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCDependencia.setForeground(new java.awt.Color(0, 0, 0));
        JCDependencia.setBorder(null);
        JCDependencia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JCDependenciaActionPerformed(evt);
            }
        });

        Clave2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave2.setForeground(new java.awt.Color(51, 51, 51));
        Clave2.setText("DEPENDENCIA");
        Clave2.setToolTipText("");

        txtNombre.setBackground(java.awt.Color.white);
        txtNombre.setColumns(45);
        txtNombre.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("Ingrese el nombre ");
        txtNombre.setBorder(null);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        Clave3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave3.setForeground(new java.awt.Color(51, 51, 51));
        Clave3.setText("DIRECCION");
        Clave3.setToolTipText("");

        JCNivel1.setBackground(new java.awt.Color(204, 204, 204));
        JCNivel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCNivel1.setForeground(new java.awt.Color(0, 0, 0));
        JCNivel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "1", "2", "3" }));
        JCNivel1.setBorder(null);
        JCNivel1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JCNivel1ActionPerformed(evt);
            }
        });

        Clave4.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave4.setForeground(new java.awt.Color(51, 51, 51));
        Clave4.setText("NIVEL");
        Clave4.setToolTipText("");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Clave1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Clave4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Clave3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(JCNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(Clave2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JCDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bgAbj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(bgArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Clave1))
                .addGap(6, 6, 6)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clave4)
                    .addComponent(Clave3))
                .addGap(4, 4, 4)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clave2)
                    .addComponent(JCDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(bgAbj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtClaveActionPerformed
    {//GEN-HEADEREND:event_txtClaveActionPerformed

    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtDireccionActionPerformed
    {//GEN-HEADEREND:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMouseEntered
    {//GEN-HEADEREND:event_btnGuardarMouseEntered
        btnGuardar.setBackground(new Color(102, 175, 240));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMouseExited
    {//GEN-HEADEREND:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(102, 153, 255));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void txtDireccionMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtDireccionMousePressed
    {//GEN-HEADEREND:event_txtDireccionMousePressed
        txtDireccion.setText("");
        txtDireccion.setForeground(Color.black);
    }//GEN-LAST:event_txtDireccionMousePressed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMouseClicked
    {//GEN-HEADEREND:event_btnGuardarMouseClicked
        //JOptionPane.showMessageDialog(this, "correcto");
        nuevo();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void JCDependenciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JCDependenciaActionPerformed
    {//GEN-HEADEREND:event_JCDependenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCDependenciaActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNombreMousePressed
    {//GEN-HEADEREND:event_txtNombreMousePressed
        txtNombre.setText("");
        txtNombre.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNombreActionPerformed
    {//GEN-HEADEREND:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void JCNivel1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JCNivel1ActionPerformed
    {//GEN-HEADEREND:event_JCNivel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCNivel1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaCrearDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaCrearDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaCrearDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaCrearDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                VentanaCrearDep dialog = new VentanaCrearDep(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter()
//                {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e)
//                    {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    private void nuevo()
    {
        if (camposValidados())
        {
            String nombre = txtNombre.getText().trim();
            String direccion = txtDireccion.getText().trim();
            String nivel = (String) JCNivel1.getSelectedItem();
            String dependencia = (String) JCDependencia.getSelectedItem();
            Hospital h=new Hospital(nivel, direccion, nombre);

            String[] ruta = new String[2];
            ruta[0]=dependencia;
            ruta[1]=nombre;
            Manipula.insertar(h, nombre, ruta);

            //NodoM nodo = Var.getM().buscarRuta(Var.getM().getR(), ruta, 0);
            //NodoM nodo = Var.getM().getR();
            NodoM nodo = Var.getM().busca(Var.getM().getR(), ruta[0]);
            DefaultTableModel modelo = Manipula.actualizarTabla(nodo);
            principal.getTbDatos().setModel(modelo);
            ManipulaTablas.personalizarTabla(principal.getTbDatos(), "Hospital");

            ManipulaArchivos.guardar(Var.getM(), "datos.dat");
            ManipulaArchivos.guardarContador(Datos.getContadorGeneral(), "contador.dat");

            VentanaCrearHos.this.dispose();
            //JOptionPane.showMessageDialog(this, "Dependencia guardada");
        } else
        {
            JOptionPane.showMessageDialog(this, "Completa todos los campos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean camposValidados()
    {
        String nivel = (String) JCNivel1.getSelectedItem();
        String dependencia = (String) JCDependencia.getSelectedItem();
        return !txtDireccion.getText().trim().isBlank() &&
               !txtNombre.getText().trim().isBlank() && 
                nivel != null && !nivel.equals("...") &&
                dependencia != null && !dependencia.equals("Selecciona...");
    }

    public static void llenarComboDependencias(JComboBox combo, NodoM n)
    {
        combo.removeAllItems();
        combo.addItem("Selecciona...");
        agregarDependencias(combo, n);
    }

    public static void agregarDependencias(JComboBox combo, NodoM n)
    {
        if (n != null)
        {
            NodoM aux = n.getSiguiente();
            do
            {
                if (aux.getObj() instanceof Dependencia)
                {
                    combo.addItem(aux.getEt());
                }
                aux=aux.getSiguiente();
            } while (aux!=n.getSiguiente());
        } else
        {
            return;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Clave1;
    private javax.swing.JLabel Clave2;
    private javax.swing.JLabel Clave3;
    private javax.swing.JLabel Clave4;
    private javax.swing.JComboBox<String> JCDependencia;
    private javax.swing.JComboBox<String> JCNivel1;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgAbj;
    private javax.swing.JPanel bgArb;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel iconPropiedas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtNombreClase;
    // End of variables declaration//GEN-END:variables
}
